/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-12/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-12_NeuronDB.dat'); exit" &

/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-13/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-13_NeuronDB.dat'); exit" &

/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-14/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-14_NeuronDB.dat'); exit" &

/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-15/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-15_NeuronDB.dat'); exit" &

/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-16/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-16_NeuronDB.dat'); exit" &

/opt/MATLAB710/bin/matlab -nodisplay -nosplash -r "addpath(genpath('~/src/BlueTools-matlab')); getPlacementRange_NoWaitbar('/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/v4_15.09.14Final_NoBadClonesMEGatedAntiStuck0_NoL6MCsubs_ih_exp_NeuronDB.dat', '/gpfs/bbp.cscs.ch/home/ebmuller/src/recipe-generation-git/densities_and_thicks/P14-17/builderRecipeAllPathways_c14n.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/bionames/placement_hints/joint_placement_rules__bio_name__13_06_2012.xml', '/gpfs/bbp.cscs.ch/release/l2/2012.07.23/morphologies/annotations', 'v4_SomatosensoryCxS1-v5_r0_P14-17_NeuronDB.dat'); exit" &

